project:
  type: book
  output-dir: docs

book:
  title: "Introduction to Stochastic Processes"
  author: "Thiyanga S. Talagala"
  search: true
  cover-image: cover.png
  chapters:
    - index.qmd
    - intro.qmd
    - chapter2.qmd
    - practical1.qmd
    - chapter5.qmd
    - chapter6.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    cover-image: cover.png
    theme: cosmo
  pdf:
    documentclass: scrreprt




